sudo: true

services:
  - docker

env:
  - IJAVA_COMPILER_OPTS="--enable-preview --source=15 --add-modules jdk.incubator.foreign"

before_install:
  - sudo apt-get install npm
  - docker pull forax/do-synthetic-methods-dream-of-electric-switch-expressions
  - docker run -d -p 8888:8888 forax/do-synthetic-methods-dream-of-electric-switch-expressions jupyter notebook -ip 0.0.0.0 --NotebookApp.token=''

install:
  - npm install decktape

script:
  - npm bin
  - node_modules/.bin/decktape rise --load-pause 1000 --pause 200 http://localhost:8888/notebooks/slideshow/chapter03-record.ipynb record.pdf
