sudo: true

services:
  - docker

before_install:
  - sudo apt-get install npm
  - docker build -f docker/Dockerfile -t forax/do-synthetic-methods-dream-of-electric-switch-expressions .
#  - docker pull forax/do-synthetic-methods-dream-of-electric-switch-expressions
  - docker run -d -p 8888:8888 forax/do-synthetic-methods-dream-of-electric-switch-expressions jupyter notebook --no-browser --ip 0.0.0.0 --NotebookApp.token="" 

install:
  - npm install decktape

script:
  - npm bin
  - node_modules/.bin/decktape rise --load-pause 1000 --pause 200 http://localhost:8888/notebooks/slideshow/chapter03-record.ipynb record.pdf
