sudo: true

language: java
jdk: openjdk11

services:
  - docker

before_install:
  - sudo apt-get install npm
  - docker build -f docker/Dockerfile -t forax/do-synthetic-methods-dream-of-electric-switch-expressions .
#  - docker pull forax/do-synthetic-methods-dream-of-electric-switch-expressions
  - docker run -d -p 8888:8888 forax/do-synthetic-methods-dream-of-electric-switch-expressions jupyter notebook --no-browser --ip 0.0.0.0 --NotebookApp.token="" 

install:
  - npm install decktape

script:
  - npm bin
  - java build/print_slideshow.java
